### ISSUE TITLE
הביקורת שלי

### ISSUE THREAD

**Issue by ehud166** [yair-go/gitExampleVS#1]
הסברים מעולים תודה רבה
תוכל להסביר גם על האפשרות לעבודה עם בראנץ' ובכללי על דחיפה לגיטהב בכל עדכון?

**Comment by yair-go** [comment]
תודה
עבודה עם בראנץ' זה חורג מהמדריך הזה

אני מתכנן להוסיף עוד על דרך העבודה הרצוי
!אבל אחד הרעיונות בגיטהאב הוא שעוד יכולים לתרום, אז מוזמן

אתה צריך לעשות 
fork למאגר הזה
pull request להוסיף אצלך עדכונים, ולשלוח
